# Generated by Django 4.1 on 2022-08-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('rent_amount', models.IntegerField(max_length=100)),
            ],
        ),
    ]
